<a href="https://colab.research.google.com/github/ollie-sr/Africa-Data-School-Curriculum/blob/main/PANDAS0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
array_1= np.array([1,2,3,4])
print("1D array:", array_1)

1D array: [1 2 3 4]


In [31]:
reshaped_array= array_1.reshape(4,1)

In [37]:
print('Reshaped array\n', reshaped_array)

Reshaped array
 [[1]
 [2]
 [3]
 [4]]


In [43]:
flattened_array= reshaped_array.flatten()

In [44]:
print('flattened array\n', flattened_array)

flattened array
 [1 2 3 4]


In [14]:
array_1[2]

3

In [15]:
array_1[-1]

4

In [17]:
array_1[1:3]

array([2, 3])

In [7]:
array_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print( array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
flattened_array_2= array_2d.flatten()

In [47]:
print(flattened_array_2)

[1 2 3 4 5 6 7 8 9]


In [18]:
array_2d[0]

array([1, 2, 3])

In [28]:
array_2d[0:2,2:]

array([[3],
       [6]])

In [29]:
array_2d[2][0]

7

In [9]:
array_3D= np.array([[[1,2]],[[3,4]],[[5,6]]])
print(array_3D)

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [56]:
flattened_array_3= array_3D.flatten("k")

In [57]:
print(flattened_array_3)

[1 2 3 4 5 6]


In [64]:
reshaped_array_3= array_3D.reshape(6,1)

In [65]:
print(reshaped_array_3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
array_1.shape

(4,)

In [11]:
print(array_1.shape,array_2d.shape,array_3D.shape)

(4,) (3, 3) (3, 1, 2)


In [13]:
print(array_1.size)
print(array_2d.size)
print(array_3D.size)

4
9
6


In [9]:
import numpy as np
u= np.array([1,2,3,4])
t= np.array([6,7,8,9])

In [11]:

multiply= u*t
print('product:', multiply)

product: [ 6 14 24 36]


In [13]:

subtraction=u-t
print('difference:\n', subtraction)


difference:
 [-5 -5 -5 -5]


In [18]:
tres=np.array(multiply)
mean= np.(multiply)
print(mean)

19.0


In [22]:
uno_1= np.array([[1,2,3],[3,4,5],[6,7,8]])
des_2= np.array([10,11,12])

In [26]:
broadcasted_sum= (uno_1+des_2)
print(broadcasted_sum)

[[11 13 15]
 [13 15 17]
 [16 18 20]]


In [27]:
z= np.array([4,9,16])
sin= np.sin(z)
print(square_root)

[-0.7568025   0.41211849 -0.28790332]


In [28]:
square_array= np.sqrt(z)
print(square_array)

[2. 3. 4.]


In [29]:
data= np.array([278,4773,373778,37237783,32723774,2373784,2328238])
print(data)

[     278     4773   373778 37237783 32723774  2373784  2328238]


In [30]:
mean= print(np.mean(data))

10720344.0


In [31]:
median= print(np.median(data))

2328238.0


In [32]:
max= print(np.max(data))

37237783


In [33]:
min= print(np.min(data))

278


In [34]:
argz= print(np.argmax(data))

3


In [35]:
pos_min= print(np.argmin(data))

0


In [39]:
difference= (np.max(data))+(np.min(data))
print(difference)

37238061


In [41]:
from scipy import stats

In [42]:
mode= stats.mode(data)
print(mode)

ModeResult(mode=278, count=1)


In [43]:
variance= np.var(data)
print (variance)

237744673532172.84


In [44]:
deviation= np.std(data)
print(deviation)

15418971.221588451


In [49]:
uniform_random= np.random.rand(9)
print(uniform_random)

[0.32468185 0.5135921  0.9928181  0.53903321 0.46475647 0.98020294
 0.33555787 0.68925487 0.65963205]


In [50]:
array_s= np.array(uniform_random)
print(array_s)

[0.32468185 0.5135921  0.9928181  0.53903321 0.46475647 0.98020294
 0.33555787 0.68925487 0.65963205]


In [55]:
array_uniform= np.random.uniform (9,10, size=5)
print(array_uniform)

[9.2909192  9.40219889 9.42539372 9.95237013 9.69564386]


In [61]:
np.random.seed(42)
array_f= np.random.normal(1,100,size=100)
print(array_f)

[  50.6714153   -12.82643012   65.76885381  153.30298564  -22.41533747
  -22.41369569  158.92128155   77.74347292  -45.94743859   55.25600436
  -45.34176928  -45.57297536   25.19622716 -190.32802447 -171.49178325
  -55.22875292 -100.28311203   32.42473326  -89.80240755 -140.23037013
  147.56487689  -21.57763005    7.75282047 -141.47481862  -53.43827245
   12.09225897 -114.09935774   38.56980183  -59.06386899  -28.16937498
  -59.17066122  186.22781845   -0.34972247 -104.7710929    83.25449121
 -121.084365     21.8863595  -194.96701239 -131.81860489   20.68612359
   74.846658     18.13682812  -10.56482824  -29.11036956 -146.85219904
  -70.98442084  -45.0638771   106.71222262   35.36182896 -175.30401554
   33.40839694  -37.50822804  -66.69220003   62.16762888  104.09995225
   94.12801191  -82.92175232  -29.92123759   34.12634314   98.55451271
  -46.91742378  -17.56589767 -109.6334974  -118.62066241   82.25258224
  136.62400286   -6.20101216  101.35328979   37.1636025   -63.51197546
   37.

In [74]:
sample_without_replace= np.random.choice(array_f,10, replace= False)
print(sample_without_replace)

[ 10.17607765  37.1636025  -37.50822804  -2.58260391 -50.82702183
  20.68612359 -69.20530939 158.92128155 106.71222262  35.36182896]


In [70]:
sample_with_replacement= np.random.choice(array_f, 10, replace=True)
print(sample_with_replacement)

[-190.32802447  147.56487689  106.71222262 -140.23037013   77.74347292
  158.92128155   -6.20101216 -100.28311203   -0.34972247  106.71222262]


In [ ]:
[-121.084365   -194.96701239  -50.82702183    1.51134566  -51.97602038
    1.51134566  -53.43827245  -69.20530939   32.42473326   36.71125715]

In [ ]:
[ -59.17066122  -82.92175232 -190.32802447   18.13682812   77.74347292
  147.56487689   27.10552722  153.30298564   35.36182896 -171.49178325]


In [76]:
print(array_f)
array_f.size

[  50.6714153   -12.82643012   65.76885381  153.30298564  -22.41533747
  -22.41369569  158.92128155   77.74347292  -45.94743859   55.25600436
  -45.34176928  -45.57297536   25.19622716 -190.32802447 -171.49178325
  -55.22875292 -100.28311203   32.42473326  -89.80240755 -140.23037013
  147.56487689  -21.57763005    7.75282047 -141.47481862  -53.43827245
   12.09225897 -114.09935774   38.56980183  -59.06386899  -28.16937498
  -59.17066122  186.22781845   -0.34972247 -104.7710929    83.25449121
 -121.084365     21.8863595  -194.96701239 -131.81860489   20.68612359
   74.846658     18.13682812  -10.56482824  -29.11036956 -146.85219904
  -70.98442084  -45.0638771   106.71222262   35.36182896 -175.30401554
   33.40839694  -37.50822804  -66.69220003   62.16762888  104.09995225
   94.12801191  -82.92175232  -29.92123759   34.12634314   98.55451271
  -46.91742378  -17.56589767 -109.6334974  -118.62066241   82.25258224
  136.62400286   -6.20101216  101.35328979   37.1636025   -63.51197546
   37.

100

In [77]:
 heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [81]:
mean_students_height= np.mean(heights)
print('mean height is:',mean_students_height)

mean height is: 166.7


In [80]:
median_students_height= np.median(heights)
print('median height is:', median_students_height)

median height is: 166.5


In [82]:
STD_DEV_Height= np.std(heights)
print('standard deviation in heights is:', STD_DEV_Height)

standard deviation in heights is: 7.5372408744845085


In [84]:
normalized_heights= ((heights-mean_students_height)/STD_DEV_Height)
print('normalized height is:', normalized_heights)

normalized height is: [-0.88891945 -1.55229217  0.70317509 -0.22554673  1.76457144 -1.15426854
  1.10119872 -0.49089581  0.57050054  0.17247691]


In [92]:
Tallest=np.argmax(heights)
shortest=np.argmin(heights)

print(f'the tallest student is: {Tallest} while the shortest student is: {shortest}')

the tallest student is: 4 while the shortest student is: 1


In [91]:
tallest_height= np.max(heights)
shortest_height= np.min(heights)
height_diff= tallest_height - shortest_height
print(f'the difference in height between the tallest and the shortest student in  is: {height_diff} cm')

the difference in height between the tallest and the shortest student in  is: 25 cm


In [100]:
from os import replace
np.random.seed(42)
select_random_heights= np.random.choice(heights,5, replace=False)
print(select_random_heights)

[171 155 158 160 163]
